### ISSUE TITLE
AssemblyGenerator: assembler para comparacion "mayor igual que" (>=) entre float

### ISSUE THREAD

**Issue by pmarconi** [Astorga-Marconi/TDS#58]

**Comment by dastorga** [comment]
Solución: 439eede7260c3a3c5298546ed8c8c68c1776dcc2
Imagen: Test de ejemplo (2.3 >= 5.8) 
![captura de pantalla de 2014-11-06 00 33 53](https://cloud.githubusercontent.com/assets/3941974/4930538/d1bbd8e8-6565-11e4-982c-79cc6e9d533f.png)

**Comment by dastorga** [comment]
Imagen: Test de ejemplo (2.3 >= 2.3) 
![captura de pantalla de 2014-11-06 00 37 22](https://cloud.githubusercontent.com/assets/3941974/4930562/3e7cdc34-6566-11e4-9d96-630dd3f09e42.png)
