### ISSUE TITLE
AssemblyGenerator: Generar assembler para FloatReturn

### ISSUE THREAD

**Issue by dastorga** [Astorga-Marconi/TDS#61]
Imagen de un ejemplo complejo:
![captura de pantalla de 2014-11-06 01 55 59](https://cloud.githubusercontent.com/assets/3941974/4931092/3a98b57e-6571-11e4-8e48-82bc9a79855e.png)
:

**Comment by dastorga** [comment]
Imagen de un ejemplo simple:
![captura de pantalla de 2014-11-06 01 59 14](https://cloud.githubusercontent.com/assets/3941974/4931110/b456abf0-6571-11e4-8471-e4855b5e832a.png)
:

**Comment by pmarconi** [comment]
cual era el problema aca? fijate si siguen estando con los ultimos cambios realizados

**Comment by pmarconi** [comment]
Bueno, ahi realice pruebas similares y no hay error.

**Comment by dastorga** [comment]
@pmarconi lo probé, anda bárbaro!
