### ISSUE TITLE
Error: nombre de labels de float repetidos cuando se manejan flotantes en dos metodos.

### ISSUE THREAD

**Issue by dastorga** [Astorga-Marconi/TDS#62]
![captura de pantalla de 2014-11-06 23 52 43](https://cloud.githubusercontent.com/assets/3941974/4947747/0cb36a9c-6610-11e4-876e-504aa7fb010a.png)

**Comment by dastorga** [comment]
Codigo:

class test_dario{

  float fun(){
    return 2.4;
  }

  void main(){ 
    float z;
    z = fun();  
    externinvk("printfloat", void, z);
  }
}

**Comment by pmarconi** [comment]
solucion https://github.com/Astorga-Marconi/TDS/commit/fd41f5481bcbe53d48c2bb92608a3e57adb1d953
